name=input("Enter your name:")
age=input("Enter your age:")
gpa=input("Enter your GPA:")

print("\n")
print("STUDENT INFORMATION")
print("----------------------")
print("Name:"+name)
print("Age:"+age)
print("GPA:"+gpa)